# Windows (MSYS2/MinGW)

CXX = g++
CC = gcc

TARGET = app.exe

INCLUDES = -Imodules \
           -Iexternal/imgui \
           -Iexternal/imgui/backends \
           -Iexternal/miniz \
           -Iexternal/tinyfiledialogs \
           -Iexternal/stb \
           -Iexternal/json

CXXFLAGS = -std=c++17 -O2 -Wall -Wextra -static-libgcc -static-libstdc++ $(INCLUDES)
CFLAGS = $(INCLUDES)

CPP_SRC = \
main.cpp \
modules/ImageLoader/ImageLoader.cpp \
modules/HtmlExporter/HtmlExporter.cpp \
modules/ProjectIO/ProjectIO.cpp \
modules/ImportIO/ImportIO.cpp \
external/imgui/imgui.cpp \
external/imgui/imgui_demo.cpp \
external/imgui/imgui_draw.cpp \
external/imgui/imgui_tables.cpp \
external/imgui/imgui_widgets.cpp \
external/imgui/backends/imgui_impl_glfw.cpp \
external/imgui/backends/imgui_impl_opengl3.cpp

C_SRC = \
external/tinyfiledialogs/tinyfiledialogs.c \
external/miniz/miniz.c \
external/miniz/miniz_tdef.c \
external/miniz/miniz_tinfl.c \
external/miniz/miniz_zip.c

CPP_OBJ = $(CPP_SRC:.cpp=.o)
C_OBJ = $(C_SRC:.c=.o)

LDFLAGS = \
    -lglfw3 \
    -lopengl32 \
    -lgdi32 \
    -luser32 \
    -lshell32 \
    -lkernel32 \
    -lcomdlg32 \
    -lole32

all: $(TARGET)

$(TARGET): $(CPP_OBJ) $(C_OBJ)
	$(CXX) $^ $(LDFLAGS) -static-libgcc -static-libstdc++ -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET)
	find . -name "*.o" -delete