name: Build Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: >
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-glfw

      - name: Verify tools
        shell: msys2 {0}
        run: |
          which gcc
          which make
          gcc --version
          make --version

      - name: Build
        shell: msys2 {0}
        run: |
          make -f Makefile.win

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PolyAnnotator-Windows
          path: app.exe